name: antarctic-dem
channels:
  - defaults
  - conda-forge
dependencies:
  - affine=2.3.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - attrs=24.2.0
  - blas=1.0
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - certifi=2024.8.30
  - cfitsio=3.470
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - fontconfig=2.14.1
  - freetype=2.12.1
  - freexl=2.0.0
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.21.0
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=73.1
  - importlib-metadata=7.0.1
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.1
  - jpeg=9e
  - json-c=0.16
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kealib=1.5.0
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libcurl=8.9.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgdal=3.6.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.20
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.1
  - libzip=1.8.0
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - minizip=4.0.3
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=4.3.6
  - poppler=22.12.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - prompt-toolkit=3.0.48
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pyparsing=3.1.2
  - python=3.9.20
  - python_abi=3.9
  - pyzmq=25.1.2
  - qhull=2020.2
  - rasterio=1.3.10
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tiledb=2.3.3
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - uriparser=0.9.7
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xerces-c=3.2.4
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - asf-search==8.0.1
      - boto3==1.35.54
      - botocore==1.35.54
      - charset-normalizer==3.4.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dateparser==1.2.0
      - dem-stitcher==0.1.dev471+g8a63244
      - fonttools==4.54.1
      - geopandas==1.0.1
      - idna==3.10
      - importlib-resources==6.4.5
      - jmespath==1.0.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - pandas==2.2.3
      - pillow==11.0.0
      - pyogrio==0.10.0
      - pyproj==3.6.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - regex==2024.9.11
      - requests==2.32.3
      - rioxarray==0.15.0
      - s3transfer==0.10.3
      - shapely==2.0.6
      - tenacity==8.2.2
      - tqdm==4.66.6
      - tzdata==2024.2
      - tzlocal==5.2
      - urllib3==1.26.20
      - xarray==2024.7.0
